// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceIncidentReducer from "../advance_incident_reducer";
import AppendRevisionReducer from "../append_revision_reducer";
import ClaimOutboxReducer from "../claim_outbox_reducer";
import CompleteAssistanceReducer from "../complete_assistance_reducer";
import CompleteDeliveryReducer from "../complete_delivery_reducer";
import ConfigurePolicyReducer from "../configure_policy_reducer";
import ConfigureSiteReducer from "../configure_site_reducer";
import CreateReportReducer from "../create_report_reducer";
import DeliverTaskReducer from "../deliver_task_reducer";
import FlagAcknowledgementTimeoutReducer from "../flag_acknowledgement_timeout_reducer";
import GrantDemoSeederReducer from "../grant_demo_seeder_reducer";
import GrantRoleReducer from "../grant_role_reducer";
import RecordDispatchRunReducer from "../record_dispatch_run_reducer";
import RecordExpertVerificationReducer from "../record_expert_verification_reducer";
import RecordFindingReducer from "../record_finding_reducer";
import RecordInterventionReducer from "../record_intervention_reducer";
import RefreshMonitoringReducer from "../refresh_monitoring_reducer";
import RegisterMediaReducer from "../register_media_reducer";
import RegisterSourceReducer from "../register_source_reducer";
import RequestFhirExportReducer from "../request_fhir_export_reducer";
import ReserveAssistanceReducer from "../reserve_assistance_reducer";
import ReserveDispatchReducer from "../reserve_dispatch_reducer";
import RetryDeadDeliveryReducer from "../retry_dead_delivery_reducer";
import SeedDemoReducer from "../seed_demo_reducer";
import SeedFlagshipReducer from "../seed_flagship_reducer";
import SeedScenarioReducer from "../seed_scenario_reducer";
import StoreWeatherReducer from "../store_weather_reducer";
import SubmitObservationReducer from "../submit_observation_reducer";
import TransitionIncidentReducer from "../transition_incident_reducer";

export type AdvanceIncidentParams = __Infer<typeof AdvanceIncidentReducer>;
export type AppendRevisionParams = __Infer<typeof AppendRevisionReducer>;
export type ClaimOutboxParams = __Infer<typeof ClaimOutboxReducer>;
export type CompleteAssistanceParams = __Infer<typeof CompleteAssistanceReducer>;
export type CompleteDeliveryParams = __Infer<typeof CompleteDeliveryReducer>;
export type ConfigurePolicyParams = __Infer<typeof ConfigurePolicyReducer>;
export type ConfigureSiteParams = __Infer<typeof ConfigureSiteReducer>;
export type CreateReportParams = __Infer<typeof CreateReportReducer>;
export type DeliverTaskParams = __Infer<typeof DeliverTaskReducer>;
export type FlagAcknowledgementTimeoutParams = __Infer<typeof FlagAcknowledgementTimeoutReducer>;
export type GrantDemoSeederParams = __Infer<typeof GrantDemoSeederReducer>;
export type GrantRoleParams = __Infer<typeof GrantRoleReducer>;
export type RecordDispatchRunParams = __Infer<typeof RecordDispatchRunReducer>;
export type RecordExpertVerificationParams = __Infer<typeof RecordExpertVerificationReducer>;
export type RecordFindingParams = __Infer<typeof RecordFindingReducer>;
export type RecordInterventionParams = __Infer<typeof RecordInterventionReducer>;
export type RefreshMonitoringParams = __Infer<typeof RefreshMonitoringReducer>;
export type RegisterMediaParams = __Infer<typeof RegisterMediaReducer>;
export type RegisterSourceParams = __Infer<typeof RegisterSourceReducer>;
export type RequestFhirExportParams = __Infer<typeof RequestFhirExportReducer>;
export type ReserveAssistanceParams = __Infer<typeof ReserveAssistanceReducer>;
export type ReserveDispatchParams = __Infer<typeof ReserveDispatchReducer>;
export type RetryDeadDeliveryParams = __Infer<typeof RetryDeadDeliveryReducer>;
export type SeedDemoParams = __Infer<typeof SeedDemoReducer>;
export type SeedFlagshipParams = __Infer<typeof SeedFlagshipReducer>;
export type SeedScenarioParams = __Infer<typeof SeedScenarioReducer>;
export type StoreWeatherParams = __Infer<typeof StoreWeatherReducer>;
export type SubmitObservationParams = __Infer<typeof SubmitObservationReducer>;
export type TransitionIncidentParams = __Infer<typeof TransitionIncidentReducer>;

