// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import GrantRoleReducer from "../grant_role_reducer";
import SeedDemoReducer from "../seed_demo_reducer";
import SubmitObservationReducer from "../submit_observation_reducer";
import TransitionIncidentReducer from "../transition_incident_reducer";

export type GrantRoleParams = __Infer<typeof GrantRoleReducer>;
export type SeedDemoParams = __Infer<typeof SeedDemoReducer>;
export type SubmitObservationParams = __Infer<typeof SubmitObservationReducer>;
export type TransitionIncidentParams = __Infer<typeof TransitionIncidentReducer>;

