// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  idempotencyKey: __t.string().primaryKey().name("idempotency_key"),
  incidentId: __t.string().name("incident_id"),
  route: __t.string(),
  status: __t.string(),
  synthetic: __t.bool(),
  at: __t.timestamp(),
});
