// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  siteId: __t.string().name("site_id"),
  reachId: __t.string().name("reach_id"),
  description: __t.string(),
  category: __t.string(),
  observedAt: __t.string().name("observed_at"),
  latitude: __t.f64(),
  longitude: __t.f64(),
  sourceLineageId: __t.string().name("source_lineage_id"),
  kind: __t.string(),
  synthetic: __t.bool(),
  contentHash: __t.string().name("content_hash"),
  validation: __t.string(),
});
