// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcknowledgeTaskReducer from "./acknowledge_task_reducer";
import AdvanceIncidentReducer from "./advance_incident_reducer";
import AppendRevisionReducer from "./append_revision_reducer";
import ClaimMissionReducer from "./claim_mission_reducer";
import ClaimOutboxReducer from "./claim_outbox_reducer";
import CompleteAssistanceReducer from "./complete_assistance_reducer";
import CompleteDeliveryReducer from "./complete_delivery_reducer";
import ConfigurePolicyReducer from "./configure_policy_reducer";
import ConfigureSiteReducer from "./configure_site_reducer";
import CreateReportReducer from "./create_report_reducer";
import DeliverTaskReducer from "./deliver_task_reducer";
import FlagAcknowledgementTimeoutReducer from "./flag_acknowledgement_timeout_reducer";
import GrantDemoSeederReducer from "./grant_demo_seeder_reducer";
import GrantRoleReducer from "./grant_role_reducer";
import RecordDispatchRunReducer from "./record_dispatch_run_reducer";
import RecordExpertVerificationReducer from "./record_expert_verification_reducer";
import RecordFindingReducer from "./record_finding_reducer";
import RecordInterventionReducer from "./record_intervention_reducer";
import RefreshMonitoringReducer from "./refresh_monitoring_reducer";
import RegisterMediaReducer from "./register_media_reducer";
import RegisterSourceReducer from "./register_source_reducer";
import RequestFhirExportReducer from "./request_fhir_export_reducer";
import RequestHealthReviewReducer from "./request_health_review_reducer";
import RequestMonitoringReducer from "./request_monitoring_reducer";
import ReserveAssistanceReducer from "./reserve_assistance_reducer";
import ReserveDispatchReducer from "./reserve_dispatch_reducer";
import RetryDeadDeliveryReducer from "./retry_dead_delivery_reducer";
import SeedDemoReducer from "./seed_demo_reducer";
import SeedFlagshipReducer from "./seed_flagship_reducer";
import SeedScenarioReducer from "./seed_scenario_reducer";
import StoreWeatherReducer from "./store_weather_reducer";
import SubmitObservationReducer from "./submit_observation_reducer";
import TransitionIncidentReducer from "./transition_incident_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AvailableMissionsRow from "./available_missions_table";
import DemoDeliveriesRow from "./demo_deliveries_table";
import DemoEvidenceRow from "./demo_evidence_table";
import DemoIncidentsRow from "./demo_incidents_table";
import DemoMissionsRow from "./demo_missions_table";
import DemoTasksRow from "./demo_tasks_table";
import HealthIncidentsRow from "./health_incidents_table";
import MonitoringSitesRow from "./monitoring_sites_table";
import MyAssistanceRow from "./my_assistance_table";
import MyEvidenceRow from "./my_evidence_table";
import MyExpertReviewsRow from "./my_expert_reviews_table";
import MyMediaRow from "./my_media_table";
import MyMissionClaimsRow from "./my_mission_claims_table";
import MyObservationsRow from "./my_observations_table";
import MyRoleRow from "./my_role_table";
import MyTasksRow from "./my_tasks_table";
import MyValidationRow from "./my_validation_table";
import OperationsAssignmentsRow from "./operations_assignments_table";
import OperationsDeliveryHistoryRow from "./operations_delivery_history_table";
import OperationsEventsRow from "./operations_events_table";
import OperationsIncidentsRow from "./operations_incidents_table";
import OperationsMissionsRow from "./operations_missions_table";
import OperationsOutboxRow from "./operations_outbox_table";
import PublicDemoEvidenceRow from "./public_demo_evidence_table";
import PublicDemoIncidentsRow from "./public_demo_incidents_table";
import ReviewObservationsRow from "./review_observations_table";
import ScienceEvidenceRow from "./science_evidence_table";
import ScienceValidationRow from "./science_validation_table";
import ServiceDispatchLaunchesRow from "./service_dispatch_launches_table";
import ServiceEvidenceRow from "./service_evidence_table";
import ServiceIncidentsRow from "./service_incidents_table";
import ServiceOutboxRow from "./service_outbox_table";
import ServicePolicyAssignmentsRow from "./service_policy_assignments_table";
import ServiceRuleExecutionsRow from "./service_rule_executions_table";
import ServiceSitesRow from "./service_sites_table";
import ServiceWeatherContextRow from "./service_weather_context_table";
import ServiceWeatherPoliciesRow from "./service_weather_policies_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  availableMissions: __table({
    name: 'available_missions',
    indexes: [
    ],
    constraints: [
    ],
  }, AvailableMissionsRow),
  demoDeliveries: __table({
    name: 'demo_deliveries',
    indexes: [
    ],
    constraints: [
    ],
  }, DemoDeliveriesRow),
  demoEvidence: __table({
    name: 'demo_evidence',
    indexes: [
    ],
    constraints: [
    ],
  }, DemoEvidenceRow),
  demoIncidents: __table({
    name: 'demo_incidents',
    indexes: [
    ],
    constraints: [
    ],
  }, DemoIncidentsRow),
  demoMissions: __table({
    name: 'demo_missions',
    indexes: [
    ],
    constraints: [
    ],
  }, DemoMissionsRow),
  demoTasks: __table({
    name: 'demo_tasks',
    indexes: [
    ],
    constraints: [
    ],
  }, DemoTasksRow),
  healthIncidents: __table({
    name: 'health_incidents',
    indexes: [
    ],
    constraints: [
    ],
  }, HealthIncidentsRow),
  monitoringSites: __table({
    name: 'monitoring_sites',
    indexes: [
    ],
    constraints: [
    ],
  }, MonitoringSitesRow),
  myAssistance: __table({
    name: 'my_assistance',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAssistanceRow),
  myEvidence: __table({
    name: 'my_evidence',
    indexes: [
    ],
    constraints: [
    ],
  }, MyEvidenceRow),
  myExpertReviews: __table({
    name: 'my_expert_reviews',
    indexes: [
    ],
    constraints: [
    ],
  }, MyExpertReviewsRow),
  myMedia: __table({
    name: 'my_media',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMediaRow),
  myMissionClaims: __table({
    name: 'my_mission_claims',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMissionClaimsRow),
  myObservations: __table({
    name: 'my_observations',
    indexes: [
    ],
    constraints: [
    ],
  }, MyObservationsRow),
  myRole: __table({
    name: 'my_role',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRoleRow),
  myTasks: __table({
    name: 'my_tasks',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTasksRow),
  myValidation: __table({
    name: 'my_validation',
    indexes: [
    ],
    constraints: [
    ],
  }, MyValidationRow),
  operationsAssignments: __table({
    name: 'operations_assignments',
    indexes: [
    ],
    constraints: [
    ],
  }, OperationsAssignmentsRow),
  operationsDeliveryHistory: __table({
    name: 'operations_delivery_history',
    indexes: [
    ],
    constraints: [
    ],
  }, OperationsDeliveryHistoryRow),
  operationsEvents: __table({
    name: 'operations_events',
    indexes: [
    ],
    constraints: [
    ],
  }, OperationsEventsRow),
  operationsIncidents: __table({
    name: 'operations_incidents',
    indexes: [
    ],
    constraints: [
    ],
  }, OperationsIncidentsRow),
  operationsMissions: __table({
    name: 'operations_missions',
    indexes: [
    ],
    constraints: [
    ],
  }, OperationsMissionsRow),
  operationsOutbox: __table({
    name: 'operations_outbox',
    indexes: [
    ],
    constraints: [
    ],
  }, OperationsOutboxRow),
  publicDemoEvidence: __table({
    name: 'public_demo_evidence',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicDemoEvidenceRow),
  publicDemoIncidents: __table({
    name: 'public_demo_incidents',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicDemoIncidentsRow),
  reviewObservations: __table({
    name: 'review_observations',
    indexes: [
    ],
    constraints: [
    ],
  }, ReviewObservationsRow),
  scienceEvidence: __table({
    name: 'science_evidence',
    indexes: [
    ],
    constraints: [
    ],
  }, ScienceEvidenceRow),
  scienceValidation: __table({
    name: 'science_validation',
    indexes: [
    ],
    constraints: [
    ],
  }, ScienceValidationRow),
  serviceDispatchLaunches: __table({
    name: 'service_dispatch_launches',
    indexes: [
    ],
    constraints: [
    ],
  }, ServiceDispatchLaunchesRow),
  serviceEvidence: __table({
    name: 'service_evidence',
    indexes: [
    ],
    constraints: [
    ],
  }, ServiceEvidenceRow),
  serviceIncidents: __table({
    name: 'service_incidents',
    indexes: [
    ],
    constraints: [
    ],
  }, ServiceIncidentsRow),
  serviceOutbox: __table({
    name: 'service_outbox',
    indexes: [
    ],
    constraints: [
    ],
  }, ServiceOutboxRow),
  servicePolicyAssignments: __table({
    name: 'service_policy_assignments',
    indexes: [
    ],
    constraints: [
    ],
  }, ServicePolicyAssignmentsRow),
  serviceRuleExecutions: __table({
    name: 'service_rule_executions',
    indexes: [
    ],
    constraints: [
    ],
  }, ServiceRuleExecutionsRow),
  serviceSites: __table({
    name: 'service_sites',
    indexes: [
    ],
    constraints: [
    ],
  }, ServiceSitesRow),
  serviceWeatherContext: __table({
    name: 'service_weather_context',
    indexes: [
    ],
    constraints: [
    ],
  }, ServiceWeatherContextRow),
  serviceWeatherPolicies: __table({
    name: 'service_weather_policies',
    indexes: [
    ],
    constraints: [
    ],
  }, ServiceWeatherPoliciesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("acknowledge_task", AcknowledgeTaskReducer),
  __reducerSchema("advance_incident", AdvanceIncidentReducer),
  __reducerSchema("append_revision", AppendRevisionReducer),
  __reducerSchema("claim_mission", ClaimMissionReducer),
  __reducerSchema("claim_outbox", ClaimOutboxReducer),
  __reducerSchema("complete_assistance", CompleteAssistanceReducer),
  __reducerSchema("complete_delivery", CompleteDeliveryReducer),
  __reducerSchema("configure_policy", ConfigurePolicyReducer),
  __reducerSchema("configure_site", ConfigureSiteReducer),
  __reducerSchema("create_report", CreateReportReducer),
  __reducerSchema("deliver_task", DeliverTaskReducer),
  __reducerSchema("flag_acknowledgement_timeout", FlagAcknowledgementTimeoutReducer),
  __reducerSchema("grant_demo_seeder", GrantDemoSeederReducer),
  __reducerSchema("grant_role", GrantRoleReducer),
  __reducerSchema("record_dispatch_run", RecordDispatchRunReducer),
  __reducerSchema("record_expert_verification", RecordExpertVerificationReducer),
  __reducerSchema("record_finding", RecordFindingReducer),
  __reducerSchema("record_intervention", RecordInterventionReducer),
  __reducerSchema("refresh_monitoring", RefreshMonitoringReducer),
  __reducerSchema("register_media", RegisterMediaReducer),
  __reducerSchema("register_source", RegisterSourceReducer),
  __reducerSchema("request_fhir_export", RequestFhirExportReducer),
  __reducerSchema("request_health_review", RequestHealthReviewReducer),
  __reducerSchema("request_monitoring", RequestMonitoringReducer),
  __reducerSchema("reserve_assistance", ReserveAssistanceReducer),
  __reducerSchema("reserve_dispatch", ReserveDispatchReducer),
  __reducerSchema("retry_dead_delivery", RetryDeadDeliveryReducer),
  __reducerSchema("seed_demo", SeedDemoReducer),
  __reducerSchema("seed_flagship", SeedFlagshipReducer),
  __reducerSchema("seed_scenario", SeedScenarioReducer),
  __reducerSchema("store_weather", StoreWeatherReducer),
  __reducerSchema("submit_observation", SubmitObservationReducer),
  __reducerSchema("transition_incident", TransitionIncidentReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

