// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  name: __t.string(),
  cityId: __t.string().name("city_id"),
  catchmentId: __t.string().name("catchment_id"),
  streamId: __t.string().name("stream_id"),
  reachId: __t.string().name("reach_id"),
  latitude: __t.f64(),
  longitude: __t.f64(),
  synthetic: __t.bool(),
});
