// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  owner: __t.identity(),
  lineage: __t.string(),
  site: __t.string(),
  category: __t.string(),
  description: __t.string(),
  observedAt: __t.string().name("observed_at"),
  createdAt: __t.timestamp().name("created_at"),
  synthetic: __t.bool(),
  supersedesId: __t.string().name("supersedes_id"),
  correctionReason: __t.string().name("correction_reason"),
  contentHash: __t.string().name("content_hash"),
});
