// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  site: __t.string(),
  state: __t.string(),
  synthetic: __t.bool(),
  policyId: __t.string().name("policy_id"),
  evidenceIds: __t.string().name("evidence_ids"),
  trace: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
