// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Incident = __t.object("Incident", {
  id: __t.string(),
  site: __t.string(),
  state: __t.string(),
  synthetic: __t.bool(),
  policyId: __t.string(),
  evidenceIds: __t.string(),
  trace: __t.string(),
  createdAt: __t.timestamp(),
});
export type Incident = __Infer<typeof Incident>;

export const IncidentEvent = __t.object("IncidentEvent", {
  id: __t.u64(),
  incidentId: __t.string(),
  fromState: __t.string(),
  toState: __t.string(),
  actor: __t.identity(),
  reason: __t.string(),
  at: __t.timestamp(),
});
export type IncidentEvent = __Infer<typeof IncidentEvent>;

export const Mission = __t.object("Mission", {
  id: __t.string(),
  incidentId: __t.string(),
  site: __t.string(),
  rationale: __t.string(),
  state: __t.string(),
  synthetic: __t.bool(),
});
export type Mission = __Infer<typeof Mission>;

export const MyObservations = __t.object("MyObservations", {});
export type MyObservations = __Infer<typeof MyObservations>;

export const MyRole = __t.object("MyRole", {});
export type MyRole = __Infer<typeof MyRole>;

export const Observation = __t.object("Observation", {
  id: __t.string(),
  owner: __t.identity(),
  lineage: __t.string(),
  site: __t.string(),
  category: __t.string(),
  description: __t.string(),
  observedAt: __t.string(),
  createdAt: __t.timestamp(),
  synthetic: __t.bool(),
  supersedesId: __t.string(),
  correctionReason: __t.string(),
  contentHash: __t.string(),
});
export type Observation = __Infer<typeof Observation>;

export const OperationsEvents = __t.object("OperationsEvents", {});
export type OperationsEvents = __Infer<typeof OperationsEvents>;

export const OperationsIncidents = __t.object("OperationsIncidents", {});
export type OperationsIncidents = __Infer<typeof OperationsIncidents>;

export const OperationsMissions = __t.object("OperationsMissions", {});
export type OperationsMissions = __Infer<typeof OperationsMissions>;

export const Outbox = __t.object("Outbox", {
  id: __t.u64(),
  kind: __t.string(),
  aggregateId: __t.string(),
  idempotencyKey: __t.string(),
  payload: __t.string(),
  status: __t.string(),
  at: __t.timestamp(),
});
export type Outbox = __Infer<typeof Outbox>;

export const PublicDemoEvidence = __t.object("PublicDemoEvidence", {});
export type PublicDemoEvidence = __Infer<typeof PublicDemoEvidence>;

export const PublicDemoIncidents = __t.object("PublicDemoIncidents", {});
export type PublicDemoIncidents = __Infer<typeof PublicDemoIncidents>;

export const PublicEvidence = __t.object("PublicEvidence", {
  id: __t.string(),
  site: __t.string(),
  category: __t.string(),
  description: __t.string(),
  observedAt: __t.string(),
  synthetic: __t.bool(),
  contentHash: __t.string(),
});
export type PublicEvidence = __Infer<typeof PublicEvidence>;

export const PublicIncident = __t.object("PublicIncident", {
  id: __t.string(),
  site: __t.string(),
  state: __t.string(),
  policyId: __t.string(),
  evidenceIds: __t.string(),
  trace: __t.string(),
  synthetic: __t.bool(),
});
export type PublicIncident = __Infer<typeof PublicIncident>;

export const ReviewObservations = __t.object("ReviewObservations", {});
export type ReviewObservations = __Infer<typeof ReviewObservations>;

export const Role = __t.object("Role", {
  identity: __t.identity(),
  kind: __t.string(),
});
export type Role = __Infer<typeof Role>;

