'use client';
import {useState} from 'react';
import {useReducer,useSpacetimeDB,useTable} from 'spacetimedb/react';
import {reducers,tables} from '@/lib/spacetime/bindings';
import {FHIR_TARGET} from '@/lib/fhir/target';
import type {FhirBundle} from '@/lib/fhir/map';
export function FhirInspector(){
  const requestExport=useReducer(reducers.requestFhirExport),[roles]=useTable(tables.myRole);
  const [demo]=useTable(tables.demoIncidents),[privateIncidents]=useTable(tables.operationsIncidents);const incidents=privateIncidents.length?privateIncidents.filter(i=>i.policyId!=='synthetic-wastewater-v1'):demo;const [selected,setSelected]=useState(''),[result,setResult]=useState<{bundle:FhirBundle;validation:{scope:string;resourceCount:number}}|null>(null),[message,setMessage]=useState('');const {token}=useSpacetimeDB();
  async function inspect(){const id=selected||incidents[0]?.id;if(!id)return;setMessage('Mapping the selected evidence packet…');try{const response=await fetch(`/api/fhir/export/${encodeURIComponent(id)}`,{headers:token?{authorization:`Bearer ${token}`}:{}});if(!response.ok)throw new Error('Unavailable');setResult(await response.json());setMessage('Export contract and reference checks passed.')}catch{setMessage('Export unavailable. Domain records and operations remain available.')}}
  return <><div className="card"><h2>Exact interoperability target</h2><p className="badge">Official fixture validator: 0 errors ? 0 warnings ? invalid fixture rejected</p><p>FHIR R4 {FHIR_TARGET.fhirVersion} · {FHIR_TARGET.guide} {FHIR_TARGET.guideVersion}</p><p className="small">Draft CI source snapshot · {FHIR_TARGET.snapshotDate}<br/>Commit <code className="hash">{FHIR_TARGET.commit}</code><br/>Compiler {FHIR_TARGET.compiler} · Official validator {FHIR_TARGET.validatorVersion}</p><p className="muted small">The OAH CI website was unavailable at build time. Profiles were compiled from the pinned official source. Environmental Location and indicator Observation profiles are used where applicable. No clinical patient records are created.</p><label htmlFor="export-incident">{['officer','admin'].includes(roles[0]?.kind||'')?'Authorized incident':'Synthetic incident'}</label><select id="export-incident" value={selected||incidents[0]?.id||''} onChange={e=>{setSelected(e.target.value);setResult(null)}}>{incidents.map(i=><option key={i.id} value={i.id}>{i.site} · {i.state}</option>)}</select><div className="actions"><button className="primary" onClick={inspect}>Generate evidence Bundle</button>{["officer","admin"].includes(roles[0]?.kind||"")&&<button className="quiet-button" onClick={async()=>{try{const incidentId=selected||incidents[0]?.id;if(!incidentId)return;await requestExport({incidentId});await fetch("/api/workflows/outbox/trigger",{method:"POST",headers:{authorization:`Bearer ${token}`}});setMessage("Delivery request recorded in the outbox. Inspect delivery status in Operations; a configured FHIR destination is required.")}catch{setMessage("Export request was rejected.")}}}>Queue authorized FHIR delivery</button>}</div>{message&&<p role="status">{message}</p>}</div>{result&&<section><h2>{result.validation.resourceCount} mapped resources</h2><div className="grid">{result.bundle.entry.map(e=><article className="card" key={e.fullUrl}><span className="badge">Synthetic · {e.resource.resourceType}</span><p className="small hash">{e.resource.id}</p></article>)}</div><p className="small muted">{result.validation.scope}</p><button className="quiet-button" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result.bundle,null,2)],{type:'application/fhir+json'}));const a=document.createElement('a');a.href=url;a.download=`limnexa-${result.bundle.id}.json`;a.click();URL.revokeObjectURL(url)}}>Download FHIR R4 Bundle</button><details><summary>Inspect payload and Provenance</summary><pre>{JSON.stringify(result.bundle,null,2)}</pre></details></section>}</>;
}
