'use client';
import {useState} from 'react';
import {useReducer,useSpacetimeDB,useTable} from 'spacetimedb/react';
import {reducers,tables} from '@/lib/spacetime/bindings';

import {ResponsibilityInbox} from './responsibility-inbox';
import {MonitoringRequest} from './monitoring-request';
export function HealthHandoff({incidentId,siteId}:{incidentId:string;siteId:string}){const request=useReducer(reducers.requestHealthReview),{token}=useSpacetimeDB(),[reason,setReason]=useState(''),[message,setMessage]=useState('');return <details><summary>Authorize environmental surveillance review</summary><p className="small">Boundary v1 requires an officer-confirmed environmental investigation with an eligible finding and an explicit handoff reason. It makes no exposure, infection, pathogen or health-risk determination.</p><label htmlFor={`health-reason-${incidentId}`}>Surveillance handoff reason</label><textarea id={`health-reason-${incidentId}`} value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000}/><button className="quiet-button" disabled={!reason.trim()} onClick={async()=>{try{await request({incidentId,reason});if(token)void fetch('/api/workflows/outbox/trigger',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({siteId})}).catch(()=>{});setMessage('Environmental surveillance handoff recorded. Delivery status remains in the outbox.')}catch{setMessage('Handoff rejected. The professional evidence boundary must be satisfied.')}}}>Authorize surveillance review</button>{message&&<p role="status">{message}</p>}</details>}
export function HealthWorkspace(){const [incidents,ready]=useTable(tables.healthIncidents),[roles]=useTable(tables.myRole);return <><p className="small">Access: {roles[0]?.kind||'citizen'}</p><p className="notice">This workspace contains only explicitly authorized environmental handoffs. It has no patient records, private citizen observations, investigator notes, or automatic clinical risk classification.</p><ResponsibilityInbox/>{ready&&!incidents.length&&<p>No authorized surveillance handoffs are visible to this device.</p>}<div className="list">{incidents.map(i=><article className="card" key={i.id}><span className="badge">{i.synthetic?'Synthetic · ':''}{i.state}</span><h2>{i.site}</h2><p>{i.reason}</p><p className="small">Boundary: {i.boundaryVersion} · Incident {i.id}</p></article>)}</div>{['health','admin'].includes(roles[0]?.kind||'')&&incidents.length>0&&<MonitoringRequest siteIds={[...new Set(incidents.map(i=>i.site))]}/>}</>}
