import {describe,it,expect} from 'vitest';
import fc from 'fast-check';
import {DEMO_POLICY,allowedTransitions,assertTransition,contentHash,evaluate,makeEvidence,validateEvidence,type ReportInput,type Weather,incidentStates} from './core';
const now='2026-10-05T12:00:00.000Z';
const report:ReportInput={id:'report-a',siteId:'DEMO-SITE-001',reachId:'DEMO-REACH-001',description:'Visible foam and unusual sewage-like odour.',category:'wastewater-indicator',observedAt:'2026-10-05T11:30:00.000Z',latitude:59.3,longitude:18.0,gpsAccuracyM:10,protocolVersion:'field-v1',mediaHashes:[],measurement:null,supersedesId:'',correctionReason:'',missionId:''};
const a=makeEvidence(report,{identity:'a',lineage:'a',synthetic:true},now),b=makeEvidence({...report,id:'report-b'},{identity:'b',lineage:'b',synthetic:true},now);
const weather:Weather={id:'weather-a',siteId:report.siteId,observedAt:now,precipitationMm:8,synthetic:true,source:'synthetic fixture',methodVersion:'demo-v1'};
describe('shared authoritative core',()=>{
  it('does not escalate unenrolled anonymous real-world lineages',()=>{const policy={...DEMO_POLICY,synthetic:false,status:'configured-local' as const};const first=makeEvidence(report,{identity:'anon-a',lineage:'anon-a',synthetic:false},now),second=makeEvidence({...report,id:'anon-b'},{identity:'anon-b',lineage:'anon-b',synthetic:false},now);expect(evaluate([first,second],[{...weather,synthetic:false}],policy,report.siteId,now).outcome).toBe('INSUFFICIENT_EVIDENCE');expect(validateEvidence(first,now,policy).assertions.find(a=>a.dimension==='provenance_completeness')?.status).toBe('warn')});
  it('requires stored weather and independent eligible reports',()=>{expect(evaluate([a,b],[weather],DEMO_POLICY,report.siteId,now).outcome).toBe('INVESTIGATION_REQUIRED');expect(evaluate([a,b],[],DEMO_POLICY,report.siteId,now).outcome).toBe('INSUFFICIENT_EVIDENCE')});
  it('does not count copied media as independent',()=>{const media=contentHash('same image');const first=makeEvidence({...report,mediaHashes:[media]},{identity:'a',lineage:'a',synthetic:true},now);const second=makeEvidence({...report,id:'copy-b',mediaHashes:[media]},{identity:'b',lineage:'b',synthetic:true},now);const trace=evaluate([first,second],[weather],DEMO_POLICY,report.siteId,now);expect(trace.independentLineages).toBe(1);expect(trace.outcome).toBe('INSUFFICIENT_EVIDENCE')});
  it('fails future-dated evidence and records all ten trust dimensions',()=>{const e=makeEvidence({...report,observedAt:'2026-10-06T12:00:00.000Z'},{identity:'a',lineage:'a',synthetic:true},now);const v=validateEvidence(e,now,DEMO_POLICY);expect(v.assertions).toHaveLength(10);expect(v.eligible).toBe(false)});
  it('routes a configured ecological indicator only to ecological responsibility',()=>{const e=makeEvidence({...report,category:'ecological',measurement:{indicator:'dissolved-oxygen',value:3,unit:'mg/L',instrumentId:'demo-probe',calibrationDate:'2026-10-01T12:00:00.000Z'}},{identity:'a',lineage:'a',synthetic:true},now);expect(evaluate([e],[],DEMO_POLICY,report.siteId,now).route).toBe('ecological-scientist')});
  it('preserves the original and excludes a superseded report from later evaluation',()=>{const revision=makeEvidence({...report,id:'revision-a',category:'other',supersedesId:a.id,correctionReason:'Correction of category'},{identity:'a',lineage:'a',synthetic:true},now);expect(evaluate([a,b,revision],[weather],DEMO_POLICY,report.siteId,now).outcome).toBe('INSUFFICIENT_EVIDENCE');expect(a.category).toBe('wastewater-indicator')});
  it('requires follow-up evidence for closure',()=>{expect(()=>assertTransition('FOLLOW_UP','CLOSED',{role:'officer',reason:'done'})).toThrow('FOLLOW_UP_EVIDENCE_REQUIRED')});
  it('AI and citizens cannot transition incidents',()=>{for(const role of ['ai','citizen'] as const)expect(()=>assertTransition('INVESTIGATION_REQUIRED','ACKNOWLEDGED',{role,reason:'received'})).toThrow('AUTHORIZATION_DENIED')});
  it('replays deterministically regardless of evidence order',()=>{fc.assert(fc.property(fc.boolean(),reverse=>{const evidence=reverse?[b,a]:[a,b];expect(evaluate(evidence,[weather],DEMO_POLICY,report.siteId,now)).toEqual(evaluate([a,b],[weather],DEMO_POLICY,report.siteId,now))}))});
  it('rejects all forbidden state pairs',()=>{fc.assert(fc.property(fc.constantFrom(...incidentStates),fc.constantFrom(...incidentStates),(from,to)=>{if(!allowedTransitions[from].includes(to))expect(()=>assertTransition(from,to,{role:'officer',reason:'test'})).toThrow('ILLEGAL_STATE_TRANSITION')}))});
});
