'use client';
import {useEffect,useState} from 'react';import {Nav,Footer} from '@/components/nav';
type Draft={site:string;description:string;category:'wastewater-indicator'|'ecological'|'other';observedAt:string};
const initial:Draft={site:'',description:'',category:'other',observedAt:''};
export default function Report(){const [draft,setDraft]=useState<Draft>(initial);const [message,setMessage]=useState('');
useEffect(()=>{try{const saved=localStorage.getItem('limnexa-draft');if(saved)setDraft(JSON.parse(saved) as Draft)}catch{}},[]);
function update(next:Draft){setDraft(next);localStorage.setItem('limnexa-draft',JSON.stringify(next));}
function save(){if(draft.site.trim().length<3||draft.description.trim().length<15||!draft.observedAt){setMessage('Add a site, time, and description of at least 15 characters.');return}setMessage('Draft saved on this device. Authoritative submission will be available when the connected database and identity service are configured.');}
return <><Nav/><main className="shell page"><span className="badge blue">Citizen field capture</span><h1>Record what you observed.</h1><p className="muted">Describe visible or sensed conditions. Do not guess unseen chemicals, pathogens, or causes. Your draft stays on this device.</p><div className="form card"><div className="field"><label htmlFor="site">Site or stream reach</label><input id="site" value={draft.site} onChange={e=>update({...draft,site:e.target.value})} placeholder="Name the location"/></div><div className="field"><label htmlFor="time">Observation time</label><input id="time" type="datetime-local" value={draft.observedAt} onChange={e=>update({...draft,observedAt:e.target.value})}/></div><div className="field"><label htmlFor="category">What kind of observation?</label><select id="category" value={draft.category} onChange={e=>update({...draft,category:e.target.value as Draft['category']})}><option value="other">Other / uncertain</option><option value="wastewater-indicator">Possible wastewater indicator</option><option value="ecological">Ecological condition</option></select></div><div className="field"><label htmlFor="description">Describe direct observations</label><textarea id="description" value={draft.description} onChange={e=>update({...draft,description:e.target.value})} placeholder="What did you see, smell, or hear?"/></div><button className="primary" type="button" onClick={save}>Save offline draft</button>{message&&<p role="status" className="notice">{message}</p>}</div><p className="muted small">Voice transcription is optional and requires a rotated ElevenLabs key. Typed capture remains available.</p></main><Footer/></>}
